CREATE TABLE `product_tbl` (
  `PRODUCT_INDEX` int(8) AUTO_INCREMENT NOT NULL,
  `PRODUCT_NAME` varchar(45) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `REGISTRANT` varchar(10) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL DEFAULT 'SYSTEM',
  `REGISTRATION_DATE` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `DELETE_FLAG` int(1) NOT NULL DEFAULT '0',
  `PRICE` decimal(10,0) NOT NULL DEFAULT '0',
  `DISCOUNT` decimal(3,0) NOT NULL DEFAULT '0',
  `PRODUCT_MENUAL` varchar(256) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  PRIMARY KEY (`PRODUCT_INDEX`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='상품 테이블'